### ISSUE TITLE
Failing to create wav file from SID dump

### ISSUE THREAD

**Issue by mwenge** [anarkiwi/desidulate#218]
I'm not having any luck with creating a wav file from the attached dump.

[sounds.sid.dump.txt](https://github.com/anarkiwi/desidulate/files/10831238/sounds.sid.dump.txt)

It was created using:

```
x64sc -sounddev dump -soundarg sounds.sid.dump bin/iridisalpha.prg
```

When I run:
```
reg2wav --wavfile sounds.wav --pal sounds.sid.dump
```

I get a file that's longer than it ought to be and silent:

```
[robert@mwenge-desktop iridisalpha (master)]$ play sounds.wav

sounds.wav:

 File Size: 5.64M     Bit Rate: 353k
  Encoding: Signed PCM    
  Channels: 1 @ 16-bit   
Samplerate: 22050Hz      
Replaygain: off         
  Duration: 00:02:07.87  

In:13.1% 00:00:16.72 [00:01:51.15] Out:369k  [      |      ] 
```

Any ideas what could be wrong with the dump file?

**Comment by mwenge** [comment]
Found it - the start of the dump has a long pause:

```
0 24 0
79127004 4 0
4 11 0
```

Thanks Rubber Ducky! :)

**Comment by anarkiwi** [comment]
Hi Rob,

Thanks for using desidulate and for including the debug!

I see from the SID dump, that there's a very long period of
executation time before any useful register changes are sent to the SID.

0 24 0
79127004 4

About a minute and half or so.

**Comment by mwenge** [comment]
Thanks Josh - in the typical fashion of bug reports I realized the issue
nearly immediately after submitting it! :)

Desidulate works very well for me now. It has definitely save me the work
of figuring out how to turn a sequence of writes to the SID registers into
a wav file - which is a good/bad thing I guess as I would definitely like
to understand the mechanics of how it works a bit better and there is a
general lack of easy documentation for someone coming to the subject
completely cold.

A very nice project all the same - well done to you!
